
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('ARS', '$', 'Peso argentino', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('BOB', 'Bs', 'Boliviano', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('BRL', 'R$', 'Real', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('CLF', 'UF', 'Unidad de Fomento', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('CLP', '$', 'Peso Chileno', 0, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('COP', '$', 'Peso colombiano', 0, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('CRC', '₡', 'Colones', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('CUC', 'CUC', 'Peso Cubano Convertible', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ('CUP', '$', 'Peso Cubano', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'DOP', '$', 'Peso Dominicano', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'EUR', '€', 'Euro', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'GTQ', 'Q', 'Quetzal Guatemalteco', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'HNL', 'L', 'Lempira', 0, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'MXN', '$', 'Peso Mexicano', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'NIO', 'C$', 'Córdoba', 0, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'PAB', 'B/.', 'Balboa', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'PEN', 'S/', 'Soles', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'PYG', '₲', 'Guaraní', 0, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'USD', 'U$S', 'Dólar', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'UYU', '$', 'Peso Uruguayo', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'VEF', 'Bs.', 'Bolivar fuerte', 2, true);
INSERT INTO currency (code, symbol, description, decimal_places, enabled) VALUES ( 'VES', 'Bs.', 'Bolivar Soberano', 2, true);


INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('AR', 'Argentina', 'es_AR', 'GMT-03:00', 1, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('AU', 'Australia', 'en_US', 'GMT+10:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('BO', 'Bolivia', 'es_BO', 'GMT-04:00', 2, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('BR', 'Brasil', 'pt_BR', 'GMT-03:00', 3, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('CA', 'Canada', 'en_US', 'GMT-04:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('CL', 'Chile', 'es_CL', 'GMT-03:00', 5, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ('CN', 'China', 'en_US', 'GMT+08:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'CO', 'Colombia', 'es_CO', 'GMT-05:00', 6, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'CR', 'Costa Rica', 'es_CR', 'GMT-06:00', 7, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'CU', 'Cuba', 'es_CU', 'GMT-05:00', 8, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'EC', 'Ecuador', 'es_EC', 'GMT-05:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'SV', 'El Salvador', 'es_SV', 'GMT-06:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'FR', 'France', 'en_US', 'GMT+02:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'DE', 'Germany', 'en_US', 'GMT+02:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'GB', 'Great Britain', 'en_US', 'GMT+01:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'GT', 'Guatemala', 'es_GT', 'GMT-06:00', 12, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'HN', 'Honduras', 'es_HN', 'GMT-06:00', 13, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'HK', 'Hong Kong', 'en_US', 'GMT+08:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'IN', 'India', 'en_US', 'GMT+05:30', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'IT', 'Italy', 'en_US', 'GMT+01:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'JP', 'Japan', 'en_US', 'GMT+09:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'MX', 'Mexico', 'es_MX', 'GMT-06:00', 14, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'NI', 'Nicaragua', 'es_NI', 'GMT-06:00', 15, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'PA', 'Panamá', 'es_PA', 'GMT-05:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'PY', 'Paraguay', 'es_PY', 'GMT-03:00', 18, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'PE', 'Peru', 'es_PE', 'GMT-05:00', 17, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'PT', 'Portugal', 'pt_PT', 'GMT+01:00', 11, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'PR', 'Puerto Rico', 'es_PR', 'GMT-06:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'DO', 'República Dominicana', 'es_DO', 'GMT-04:00', 10, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'KR', 'South Korea', 'en_US', 'GMT+09:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'ES', 'Spain', 'en_US', 'GMT+01:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'TR', 'Turkey', 'en_US', 'GMT+03:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'US', 'United States of America', 'en_US', 'GMT-04:00', 19, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'UY', 'Uruguay', 'es_UY', 'GMT-03:00', 20, true);
INSERT INTO country (code, name, locale, time_zone, currency_id, enabled) VALUES ( 'VE', 'Venezuela', 'es_VE', 'GMT-04:00', 22, true);


INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-B', 'Buenos Aires', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-C', 'Capital Federal', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-K', 'Catamarca', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-H', 'Chaco', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-U', 'Chubut', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-W', 'Corrientes', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-X', 'Córdoba', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-E', 'Entre Ríos', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ('AR-P', 'Formosa', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-Y', 'Jujuy', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-L', 'La Pampa', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-F', 'La Rioja', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-M', 'Mendoza', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-N', 'Misiones', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-Q', 'Neuquén', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-R', 'Río Negro', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-A', 'Salta', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-J', 'San Juan', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-D', 'San Luis', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-Z', 'Santa Cruz', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-S', 'Santa Fe', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-G', 'Santiago del Estero', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-V', 'Tierra del Fuego', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AR-T', 'Tucumán', true, 1);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-ACT', 'Aust Capit Territory', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-NSW', 'New South Wales', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-NT', 'Northern Territory', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-QLD', 'Queensland', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-SA', 'South Australia', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-TAS', 'Tasmania', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-VIC', 'Victoria', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'AU-WA', 'Western Australia', true, 2);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-B', 'Beni', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-H', 'Chuquisaca', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-C', 'Cochabamba', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-L', 'La Paz', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-O', 'Oruro', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-N', 'Pando', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-P', 'Potosí', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-S', 'Santa Cruz', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BO-T', 'Tarija', true, 3);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-AC', 'Acre', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-AL', 'Alagoas', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-AP', 'Amapá', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-AM', 'Amazonas', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-BA', 'Bahia', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-CE', 'Ceará', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-DF', 'Distrito Federal', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-ES', 'Espírito Santo', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-GO', 'Goiás', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-MA', 'Maranhão', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-MT', 'Mato Grosso', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-MS', 'Mato Grosso do Sul', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-MG', 'Minas Gerais', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-PR', 'Paraná', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-PB', 'Paraíba', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-PA', 'Pará', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-PE', 'Pernambuco', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-PI', 'Piauí', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-RN', 'Rio Grande do Norte', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-RS', 'Rio Grande do Sul', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-RJ', 'Rio de Janeiro', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-RO', 'Rondônia', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-RR', 'Roraima', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-SC', 'Santa Catarina', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-SE', 'Sergipe', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-SP', 'São Paulo', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'BR-TO', 'Tocantins', true, 4);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-AB', 'Alberta', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-BC', 'British Columbia', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-MB', 'Manitoba', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-NB', 'New Brunswick', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-NL', 'Newfoundland and Lab', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-NT', 'Northwest Territorie', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-NS', 'Nova Scotia', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-NU', 'Nunavut', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-ON', 'Ontario', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-PE', 'Prince Edward Island', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-QC', 'Quebec', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CA-YT', 'Yukon', true, 5);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-AI', 'Aysén', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-AN', 'Antofagasta', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-AP', 'Arica y Parinacota', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-AT', 'Atacama', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-BI', 'Biobío', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-CO', 'Coquimbo', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-AR', 'La Araucanía', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-LI', 'Libertador B. O''Higgins', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-LL', 'Los Lagos', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-LR', 'Los Ríos', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-MA', 'Magallanes', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-ML', 'Maule', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-RM', 'RM (Metropolitana)', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-TA', 'Tarapacá', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-VS', 'Valparaíso', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CL-NB', 'Ñuble', true, 6);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-AH', 'Anhui', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-BJ', 'Beijing', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-CQ', 'Chongqing', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-FJ', 'Fujian', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-GS', 'Gansu', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-GD', 'Guangdong', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-GX', 'Guangxi', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-GZ', 'Guizhou', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-HI', 'Hainan', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-HE', 'Hebei', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-HL', 'Heilongjiang', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-HA', 'Henan', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-HB', 'Hubei', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-HN', 'Hunan', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-NM', 'Inner Mongolia', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-JS', 'Jiangsu', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-JX', 'Jiangxi', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-JL', 'Jilin', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-LN', 'Liaoning', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-NX', 'Ningxia', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-QH', 'Qinghai', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-SN', 'Shaanxi', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-SD', 'Shandong', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-SH', 'Shanghai', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-SX', 'Shanxi', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-SC', 'Sichuan', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-TJ', 'Tianjin', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-XJ', 'Xinjiang', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-XZ', 'Xizang', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-YN', 'Yunnan', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CN-ZJ', 'Zhejiang', true, 7);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-AMA', 'Amazonas', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-ANT', 'Antioquia', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-ARA', 'Arauca', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-ATL', 'Atlantico', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-DC', 'Bogotá D.C.', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-BOL', 'Bolivar', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-BOY', 'Boyaca', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CAL', 'Caldas', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CAQ', 'Caqueta', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CAS', 'Casanare', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CAU', 'Cauca', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CES', 'Cesar', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CHO', 'Choco', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-CUN', 'Cundinamarca', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-COR', 'Córdoba', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-GUA', 'Guainía', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-LAG', 'Guajira', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-GUV', 'Guaviare', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-HUI', 'Huila', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-MAG', 'Magdalena', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-MET', 'Meta', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-NAR', 'Nariño', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-NSA', 'Norte De Santander', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-PUT', 'Putumayo', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-QUI', 'Quindio', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-RIS', 'Risaralda', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-SAP', 'San Andres y Providencia', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-SAN', 'Santander', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-SUC', 'Sucre', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-TOL', 'Tolima', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-VAC', 'Valle Del Cauca', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-VAU', 'Vaupes', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CO-VID', 'Vichada', true, 8);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-A', 'Alajuela', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-C', 'Cartago', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-G', 'Guanacaste', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-H', 'Heredia', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-L', 'Limón', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-P', 'Puntarenas', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CR-SJ', 'San José', true, 9);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-15', 'Artemisa', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-09', 'Camagüey', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-08', 'Ciego de Ávila', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-06', 'Cienfuegos', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-12', 'Granma', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-14', 'Guantánamo', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-11', 'Holguín', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-99', 'Isla de la Juventud', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-02', 'La Habana', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-10', 'Las Tunas', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-04', 'Matanzas', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-16', 'Mayabeque', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-01', 'Pinar del Río', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-07', 'Sancti Spíritus', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-13', 'Santiago de Cuba', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'CU-05', 'Villa Clara', true, 10);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-A', 'Azuay', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-B', 'Bolívar', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-C', 'Carchi', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-F', 'Cañar', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-H', 'Chimborazo', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-X', 'Cotopaxi', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-O', 'El Oro', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-E', 'Esmeraldas', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-W', 'Galápagos', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-YQ', 'Guayaquil', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-G', 'Guayas', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-I', 'Imbabura', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-L', 'Loja', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-R', 'Los Ríos', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-M', 'Manabí', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-S', 'Morona Santiago', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-N', 'Napo', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-D', 'Orellana', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-Y', 'Pastaza', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-P', 'Pichincha ( Quito )', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-Q', 'Quito', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-SE', 'Santa Elena', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-SD', 'Santo Domingo de los Tsáchilas', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-U', 'Sucumbíos', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-T', 'Tungurahua', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'EC-Z', 'Zamora Chinchipe', true, 11);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-AH', 'Ahuachapán', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-CA', 'Cabañas', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-CH', 'Chalatenango', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-CU', 'Cuscatlán', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-LI', 'La Libertad', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-PA', 'La Paz', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-UN', 'La Unión', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-MO', 'Morazán', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-SM', 'San Miguel', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-SS', 'San Salvador', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-SV', 'San Vicente', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-SA', 'Santa Ana', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-SO', 'Sonsonate', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'SV-US', 'Usulután', true, 12);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-PAC', 'Prov-Alpes-Côte-d’Az', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-BFC', 'Bourgogne-Franche-Co', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-01', 'Ain', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-02', 'Aisne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-03', 'Allier', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-04', 'Alpes-de-Haute-Prov', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-05', 'Hautes-Alpes', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-06', 'Alpes-Maritimes', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-07', 'Ardèche', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-08', 'Ardennes', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-09', 'Ariège', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-10', 'Aube', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-11', 'Aude', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-12', 'Aveyron', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-13', 'Bouches-du-Rhône', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-14', 'Calvados', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-15', 'Cantal', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-16', 'Charente', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-17', 'Charente-Maritime', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-18', 'Cher', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-19', 'Corrèze', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-21', 'Côte-d''Or', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-22', 'Côtes-d''Armor', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-23', 'Creuse', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-24', 'Dordogne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-25', 'Doubs', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-26', 'Drôme', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-27', 'Eure', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-28', 'Eure-et-Loir', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-29', 'Finistère', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-30', 'Gard', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-31', 'Haute-Garonne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-32', 'Gers', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-33', 'Gironde', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-34', 'Hérault', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-35', 'Ille-et-Vilaine', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-36', 'Indre', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-37', 'Indre-et-Loire', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-38', 'Isère', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-39', 'Jura', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-40', 'Landes', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-41', 'Loir-et-Cher', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-42', 'Loire', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-43', 'Haute-Loire', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-44', 'Loire-Atlantique', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-45', 'Loiret', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-46', 'Lot', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-47', 'Lot-et-Garonne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-48', 'Lozère', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-49', 'Maine-et-Loire', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-50', 'Manche', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-51', 'Marne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-52', 'Haute-Marne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-53', 'Mayenne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-54', 'Meurthe-et-Moselle', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-55', 'Meuse', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-56', 'Morbihan', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-57', 'Moselle', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-58', 'Nièvre', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-59', 'Nord', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-60', 'Oise', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-61', 'Orne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-62', 'Pas-de-Calais', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-63', 'Puy-de-Dôme', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-64', 'Pyrénées-Atlantiques', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-65', 'Hautes-Pyrénées', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-66', 'Pyrénées-Orientales', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-67', 'Bas-Rhin', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-68', 'Haut-Rhin', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-69', 'Rhône', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-70', 'Haute-Saône', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-71', 'Saône-et-Loire', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-72', 'Sarthe', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-73', 'Savoie', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-74', 'Haute-Savoie', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-75', 'Paris', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-76', 'Seine-Maritime', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-77', 'Seine-et-Marne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-78', 'Yvelines', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-79', 'Deux-Sèvres', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-80', 'Somme', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-81', 'Tarn', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-82', 'Tarn-et-Garonne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-83', 'Var', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-84', 'Vaucluse', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-85', 'Vendée', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-86', 'Vienne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-87', 'Haute-Vienne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-88', 'Vosges', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-89', 'Yonne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-90', 'Territoire de Belf', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-91', 'Essonne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-92', 'Hauts-de-Seine', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-93', 'Seine-Saint-Denis', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-94', 'Val-de-Marne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-ARA', 'Auvergne-Rhône-Alpes', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-BL', 'Saint-Barthélemy', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-BRE', 'Bretagne', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-COR', 'Corse', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-CVL', 'Centre-Val de Loire', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-GES', 'Grand-Est', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-GF', 'Guyane', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-HDF', 'Hauts-de-France', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-IDF', 'Île-de-France', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-NAQ', 'Nouvelle-Aquitaine', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-NOR', 'Normandie', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-OCC', 'Occitanie', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'FR-95', 'Val-d''Oise', true, 13);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-NW', 'North Rhine West', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-BW', 'Baden-Wurtemberg', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-BY', 'Baviera', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-BB', 'Brandeburgo', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-HB', 'Bremen', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-HH', 'Hamburgo', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-HE', 'Hesse', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-NI', 'Lower Saxony', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-MV', 'Mecklenburg-Vorpo', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-RP', 'Rhineland-Palatinate', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-SL', 'Saarland', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-SN', 'Saxony', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-ST', 'Sajonia-Anhalt', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-SH', 'Schleswig-Holstein', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DE-TH', 'Thuringia', true, 14);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GB-ENG', 'England', true, 15);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GB-NIR', 'Northern Ireland', true, 15);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GB-SCT', 'Scotland', true, 15);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GB-WLS', 'Wales', true, 15);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-AV', 'Alta Verapaz', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-BV', 'Baja Verapaz', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-CM', 'Chimaltenango', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-CQ', 'Chiquimula', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-PR', 'El Progreso', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-ES', 'Escuintla', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-GU', 'Guatemala', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-HU', 'Huehuetenango', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-IZ', 'Izabal', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-JA', 'Jalapa', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-JU', 'Jutiapa', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-PE', 'Petén', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-QZ', 'Quetzaltenango', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-QC', 'Quiché', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-RE', 'Retalhuleu', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-SA', 'Sacatepéquez', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-SM', 'San Marcos', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-SR', 'Santa Rosa', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-SO', 'Sololá', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-SU', 'Suchitepéquez', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-TO', 'Totonicapán', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'GT-ZA', 'Zacapa', true, 16);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-AT', 'Atlántida', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-CH', 'Choluteca', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-CL', 'Colón', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-CM', 'Comayagua', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-CP', 'Copán', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-CR', 'Cortés', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-EP', 'El Paraíso', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-FM', 'Francisco Morazán', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-GD', 'Gracias a Dios', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-IN', 'Intibucá', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-IB', 'Islas de la Bahía', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-LP', 'La Paz', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-LE', 'Lempira', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-OC', 'Ocotepeque', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-OL', 'Olancho', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-SB', 'Santa Bárbara', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-VA', 'Valle', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HN-YO', 'Yoro', true, 17);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'HK-HK', 'Hong Kong', true, 18);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-AP', 'Andhra Pradesh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-AR', 'Arunachal Pradesh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-AS', 'Assam', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-BR', 'Bihar', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-CH', 'Chandigarh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-CT', 'Chhattisgarh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-DN', 'Dadra And Nagar Haveli', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-DL', 'Delhi', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-GA', 'Goa', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-GJ', 'Gujarat', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-HR', 'Haryana', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-HP', 'Himachal Pradesh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-AN', 'Andaman And Nicobar Islands', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-JK', 'Jammu And Kashmir', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-JH', 'Jharkhand', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-KA', 'Karnataka', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-KL', 'Kerala', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-MP', 'Madhya Pradesh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-MH', 'Maharashtra', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-MN', 'Manipur', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-ML', 'Meghalaya', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-MZ', 'Mizoram', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-NL', 'Nagaland', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-OR', 'Odisha', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-PY', 'Puducherry', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-PB', 'Punjab', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-RJ', 'Rajasthan', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-TN', 'Tamil Nadu', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-TG', 'Telangana', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-TR', 'Tripura', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-UP', 'Uttar Pradesh', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-UT', 'Uttarakhand', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IN-WB', 'West Bengal', true, 19);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AG', 'Agrigento', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AL', 'Alessandria', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AN', 'Ancona', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AO', 'Aosta', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AR', 'Arezzo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AP', 'Ascoli Piceno', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AT', 'Asti', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AV', 'Avellino', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BA', 'Bari', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BL', 'Belluno', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BN', 'Benevento', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BI', 'Biella', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BO', 'Bolonia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BZ', 'Bolzano', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BS', 'Brescia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BR', 'Brindisi', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-BG', 'Bérgamo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CA', 'Cagliari', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CL', 'Caltanissetta', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CB', 'Campobasso', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CI', 'Carbonia-Iglesias', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CE', 'Caserta', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CT', 'Catania', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CZ', 'Catanzaro', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CH', 'Chieti', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CO', 'Como', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CS', 'Cosenza', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CR', 'Cremona', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-KR', 'Crotone', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-CN', 'Cuneo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-EN', 'Enna', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-FM', 'Fermo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-FE', 'Ferrara', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-FI', 'Florencia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-FG', 'Foggia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-FO', 'Forlí-Cesena', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-FR', 'Frosinone', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-GO', 'Gorizia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-GR', 'Grosseto', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-GE', 'Génova', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-IM', 'Imperia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-IS', 'Isernia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-AQ', 'L''Aquila', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SP', 'La Spezia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-LT', 'Latina', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-LE', 'Lecce', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-LC', 'Lecco', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-LI', 'Livorno', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-LO', 'Lodi', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-LU', 'Lucca', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-MC', 'Macerata', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-MN', 'Mantua', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-MS', 'Massa-Carrara', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-MT', 'Matera', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VS', 'Medio Campidano', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-ME', 'Mesina', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-MI', 'Milán', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-MO', 'Módena', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-NO', 'Novara', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-NU', 'Nuoro', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-NA', 'Nápoles', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-OG', 'Ogliastra', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-OT', 'Olbia-Tempio', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-OR', 'Oristano', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PD', 'Padua', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PA', 'Palermo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PR', 'Parma', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PV', 'Pavía', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PG', 'Perugia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PS', 'Pesaro y Urbino', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PE', 'Pescara', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PC', 'Piacenza', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PI', 'Pisa', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PT', 'Pistoia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PN', 'Pordenone', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PZ', 'Potenza', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-PO', 'Prato', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RG', 'Ragusa', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RE', 'Reggio Emilia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RC', 'Regio de Calabria', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RI', 'Rieti', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RM', 'Roma', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RO', 'Rovigo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RA', 'Rávena', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-RN', 'Rímini', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SA', 'Salerno', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SV', 'Savona', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SI', 'Siena', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SR', 'Siracusa', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SO', 'Sondrio', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-SS', 'Sácer', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TA', 'Tarento', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TE', 'Teramo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TR', 'Terni', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TP', 'Trapani', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TN', 'Trento', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TV', 'Treviso', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TS', 'Trieste', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-TO', 'Turín', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-UD', 'Udine', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VA', 'Varese', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VE', 'Venecia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VB', 'Verbano-Cusio-Ossola', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VC', 'Vercelli', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VR', 'Verona', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VV', 'Vibo Valentia', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VI', 'Vicenza', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'IT-VT', 'Viterbo', true, 20);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-23', 'Aichi', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-05', 'Akita', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-02', 'Aomori', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-12', 'Chiba', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-38', 'Ehime', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-18', 'Fukui', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-40', 'Fukuoka', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-07', 'Fukushima', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-21', 'Gifu', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-10', 'Gunma', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-34', 'Hiroshima', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-01', 'Hokkaidō', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-28', 'Hyōgo', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-08', 'Ibaraki', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-17', 'Ishikawa', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-03', 'Iwate', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-37', 'Kagawa', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-46', 'Kagoshima', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-14', 'Kanagawa', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-26', 'Kioto', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-43', 'Kumamoto', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-39', 'Kōchi', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-24', 'Mie', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-04', 'Miyagi', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-45', 'Miyazaki', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-20', 'Nagano', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-42', 'Nagasaki', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-29', 'Nara', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-15', 'Niigata', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-33', 'Okayama', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-47', 'Okinawa', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-27', 'Osaka', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-41', 'Saga', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-11', 'Saitama', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-25', 'Shiga', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-32', 'Shimane', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-22', 'Shizuoka', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-09', 'Tochigi', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-36', 'Tokushima', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-31', 'Tottori', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-16', 'Toyama', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-13', 'Tōkyō', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-30', 'Wakayama', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-06', 'Yamagata', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-35', 'Yamaguchi', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-19', 'Yamanashi', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'JP-44', 'Ōita', true, 21);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-AGU', 'Aguascalientes', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-BCN', 'Baja California', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-BCS', 'Baja California Sur', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-CAM', 'Campeche', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-CHP', 'Chiapas', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-CHH', 'Chihuahua', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-COA', 'Coahuila', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-COL', 'Colima', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-DIF', 'Distrito Federal', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-DUR', 'Durango', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-MEX', 'Estado De México', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-GUA', 'Guanajuato', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-GRO', 'Guerrero', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-HID', 'Hidalgo', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-JAL', 'Jalisco', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-MIC', 'Michoacán', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-MOR', 'Morelos', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-NAY', 'Nayarit', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-NLE', 'Nuevo León', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-OAX', 'Oaxaca', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-PUE', 'Puebla', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-QUE', 'Querétaro', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-ROO', 'Quintana Roo', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-SLP', 'San Luis Potosí', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-SIN', 'Sinaloa', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-SON', 'Sonora', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-TAB', 'Tabasco', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-TAM', 'Tamaulipas', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-TLA', 'Tlaxcala', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-VER', 'Veracruz', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-YUC', 'Yucatán', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'MX-ZAC', 'Zacatecas', true, 22);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-AN', 'Atlántico Norte', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-AS', 'Atlántico Sur', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-BO', 'Boaco', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-CA', 'Carazo', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-CI', 'Chinandega', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-CO', 'Chontales', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-ES', 'Estelí', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-GR', 'Granada', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-JI', 'Jinotega', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-LE', 'León', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-MD', 'Madriz', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-MN', 'Managua', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-MS', 'Masaya', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-MT', 'Matagalpa', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-NS', 'Nueva Segovia', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-RI', 'Rivas', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'NI-SJ', 'Río San Juan', true, 23);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-1', 'Bocas del Toro', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-4', 'Chiriquí', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-2', 'Coclé', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-3', 'Colón', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-5', 'Darién', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-EM', 'Emberá', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-6', 'Herrera', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-7', 'Los Santos', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-NB', 'Ngöbe-Buglé', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-8', 'Panamá', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-KY', 'San Blas', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PA-9', 'Veraguas', true, 24);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-16', 'Alto Paraguay', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-10', 'Alto Paraná', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-13', 'Amambay', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-ASU', 'Asunción D.C.', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-19', 'Boquerón', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-5', 'Caaguazú', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-6', 'Caazapá', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-14', 'Canindeyú', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-11', 'Central', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-1', 'Concepción', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-3', 'Cordillera', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-4', 'Guairá', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-7', 'Itapúa', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-8', 'Misiones', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-9', 'Paraguarí', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-15', 'Presidente Hayes', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-2', 'San Pedro', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PY-12', 'Ñeembucú', true, 25);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-AMA', 'Amazonas', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-ANC', 'Ancash', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-APU', 'Apurimac', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-ARE', 'Arequipa', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-AYA', 'Ayacucho', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-CAJ', 'Cajamarca', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-CUS', 'Cusco', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-HUV', 'Huancavelica', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-HUC', 'Huanuco', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-ICA', 'Ica', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-JUN', 'Junin', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-LAL', 'La Libertad', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-LAM', 'Lambayeque', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-LMA', 'Lima Metropolitana', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-LIM', 'Lima Provincias', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-LOR', 'Loreto', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-MDD', 'Madre De Dios', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-MOQ', 'Moquegua', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-PAS', 'Pasco', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-PIU', 'Piura', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-PUN', 'Puno', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-SAM', 'San Martin', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-TAC', 'Tacna', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-TUM', 'Tumbes', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PE-UCA', 'Ucayali', true, 26);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-01', 'Aveiro', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-02', 'Beja', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-03', 'Braga', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-04', 'Bragança', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-05', 'Castelo Branco', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-06', 'Coimbra', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-08', 'Faro', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-09', 'Guarda', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-30', 'Ilha da Madeira', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-20', 'Ilhas dos Açores', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-10', 'Leiria', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-11', 'Lisboa', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-12', 'Portalegre', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-13', 'Porto', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-14', 'Santarém', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-15', 'Setúbal', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-16', 'Viana do Castelo', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-17', 'Vila Real', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-18', 'Viseu', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'PT-07', 'Évora', true, 27);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-02', 'Azua', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-03', 'Baoruco', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-04', 'Barahona', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-05', 'Dajabón', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-01', 'Distrito Nacional', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-06', 'Duarte', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-08', 'El Seibo', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-07', 'Elías Piña', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-09', 'Espaillat', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-30', 'Hato Mayor', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-10', 'Independencia', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-11', 'La Altagracia', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-12', 'La Romana', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-13', 'La Vega', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-14', 'María Trinidad Sánchez', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-28', 'Monseñor Nouel', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-29', 'Monte Plata', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-15', 'Montecristi', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-16', 'Pedernales', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-17', 'Peravia', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-18', 'Puerto Plata', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-19', 'Salcedo', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-20', 'Samaná', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-21', 'San Cristóbal', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-31', 'San José de Ocoa', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-22', 'San Juan', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-23', 'San Pedro de Macorís', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-25', 'Santiago', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-26', 'Santiago Rodríguez', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-32', 'Santo Domingo', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-24', 'Sánchez Ramírez', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'DO-27', 'Valverde', true, 29);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-26', 'Busan', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-27', 'Daegu', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-30', 'Daejeon', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-42', 'Gangwon', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-29', 'Gwangju', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-41', 'Gyeonggi', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-28', 'Incheon', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-49', 'Jeju', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-43', 'North Chungcheong', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-47', 'North Gyeongsang', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-45', 'North Jeolla', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-50', 'Sejong', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-11', 'Seoul', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-44', 'South Chungcheong', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-48', 'South Gyeongsang', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-46', 'South Jeolla', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'KR-31', 'Ulsan', true, 30);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-AB', 'Albacete', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-A', 'Alicante', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-AL', 'Almería', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-O', 'Asturias', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-BA', 'Badajoz', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-PM', 'Baleares', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-B', 'Barcelona', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-BI', 'Bizkaia', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-BU', 'Burgos', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-S', 'Cantabria', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-CS', 'Castellón', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-CR', 'Ciudad Real', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-CU', 'Cuenca', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-CC', 'Cáceres', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-CA', 'Cádiz', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-CO', 'Córdoba', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-GI', 'Gerona', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-SS', 'Gipuzkoa', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-GR', 'Granada', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-GU', 'Guadalajara', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-H', 'Huelva', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-HU', 'Huesca', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-J', 'Jaén', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-C', 'La Coruña', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-LO', 'La Rioja', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-GC', 'Las Palmas', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-LE', 'León', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-LU', 'Lugo', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-L', 'Lérida', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-M', 'Madrid', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-MU', 'Murcia', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-MA', 'Málaga', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-NA', 'Navarra', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-OR', 'Orense', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-P', 'Palencia', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-PO', 'Pontevedra', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-SA', 'Salamanca', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-TF', 'Santa Cruz de Tenerife', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-SG', 'Segovia', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-SE', 'Sevilla', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-SO', 'Soria', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-T', 'Tarragona', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-TE', 'Teruel', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-TO', 'Toledo', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-V', 'Valencia', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-VA', 'Valladolid', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-ZA', 'Zamora', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-Z', 'Zaragoza', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-VI', 'Álava', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'ES-AV', 'Ávila', true, 31);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-01', 'Adana', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-02', 'Adıyaman', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-03', 'Afyonkarahisar', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-68', 'Aksaray', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-05', 'Amasya', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-06', 'Ankara', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-07', 'Antalya', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-75', 'Ardahan', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-08', 'Artvin', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-09', 'Aydın', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-04', 'Ağrı', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-10', 'Balıkesir', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-74', 'Bartın', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-72', 'Batman', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-69', 'Bayburt', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-11', 'Bilecik', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-12', 'Bingöl', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-13', 'Bitlis', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-14', 'Bolu', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-15', 'Burdur', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-16', 'Bursa', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-20', 'Denizli', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-21', 'Diyarbakır', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-81', 'Düzce', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-22', 'Edirne', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-23', 'Elazığ', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-24', 'Erzincan', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-25', 'Erzurum', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-26', 'Eskişehir', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-35', 'Esmirna', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-34', 'Estambul', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-27', 'Gaziantep', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-28', 'Giresun', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-29', 'Gümüşhane', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-30', 'Hakkâri', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-31', 'Hatay', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-32', 'Isparta', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-76', 'Iğdır', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-46', 'Kahramanmaraş', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-78', 'Karabük', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-70', 'Karaman', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-36', 'Kars', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-37', 'Kastamonu', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-38', 'Kayseri', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-79', 'Kilis', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-39', 'Kirklareli', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-41', 'Kocaeli', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-42', 'Konya', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-43', 'Kütahya', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-71', 'Kırıkkale', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-40', 'Kırşehir', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-44', 'Malatya', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-45', 'Manisa', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-47', 'Mardin', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-33', 'Mersin', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-49', 'Mus', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-48', 'Muğla', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-50', 'Nevsehir', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-51', 'Niğde', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-52', 'Ordu', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-80', 'Osmaniye', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-53', 'Rize', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-54', 'Sakarya', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-55', 'Samsun', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-56', 'Siirt', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-57', 'Sinope', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-58', 'Sivas', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-59', 'Tekirdağ', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-60', 'Tokat', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-61', 'Trebisonda', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-62', 'Tunceli', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-64', 'Uşak', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-65', 'Van', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-77', 'Yalova', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-66', 'Yozgat', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-67', 'Zonguldak', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-17', 'Çanakkale', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-18', 'Çankiri', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-19', 'Çorum', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-63', 'Şanlıurfa', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'TR-73', 'Şırnak', true, 32);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-AL', 'Alabama', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-AK', 'Alaska', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-AZ', 'Arizona', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-AR', 'Arkansas', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-CA', 'California', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-CO', 'Colorado', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-CT', 'Connecticut', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-DE', 'Delaware', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-DC', 'District of Columbia', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-FL', 'Florida', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-GA', 'Georgia', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-HI', 'Hawaii', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-ID', 'Idaho', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-IL', 'Illinois', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-IN', 'Indiana', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-IA', 'Iowa', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-KS', 'Kansas', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-KY', 'Kentucky', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-LA', 'Louisiana', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-ME', 'Maine', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MD', 'Maryland', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MA', 'Massachusetts', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MI', 'Michigan', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MN', 'Minnesota', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MS', 'Mississippi', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MO', 'Missouri', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-MT', 'Montana', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NE', 'Nebraska', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NV', 'Nevada', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NH', 'New Hampshire', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NJ', 'New Jersey', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NM', 'New Mexico', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NY', 'New York', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-NC', 'North Carolina', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-ND', 'North Dakota', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-OH', 'Ohio', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-OK', 'Oklahoma', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-OR', 'Oregon', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-PA', 'Pennsylvania', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-PR', 'Puerto Rico', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-RI', 'Rhode Island', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-SC', 'South Carolina', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-SD', 'South Dakota', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-TN', 'Tennessee', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-TX', 'Texas', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-UT', 'Utah', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-VT', 'Vermont', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-VI', 'Virgin Islands', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-VA', 'Virginia', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-WA', 'Washington', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-WV', 'West Virginia', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-WI', 'Wisconsin', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'US-WY', 'Wyoming', true, 33);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-AR', 'Artigas', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-CA', 'Canelones', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-CL', 'Cerro Largo', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-CO', 'Colonia', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-DU', 'Durazno', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-FS', 'Flores', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-FD', 'Florida', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-LA', 'Lavalleja', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-MA', 'Maldonado', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-MO', 'Montevideo', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-PA', 'Paysandú', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-RV', 'Rivera', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-RO', 'Rocha', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-RN', 'Río Negro', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-SA', 'Salto', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-SJ', 'San José', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-SO', 'Soriano', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-TA', 'Tacuarembó', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'UY-TT', 'Treinta y Tres', true, 34);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-Z', 'Amazonas', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-B', 'Anzoátegui', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-C', 'Apure', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-D', 'Aragua', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-E', 'Barinas', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-F', 'Bolívar', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-G', 'Carabobo', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-H', 'Cojedes', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-Y', 'Delta Amacuro', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-W', 'Depend. Federales', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-A', 'Distrito Capital', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-I', 'Falcón', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-J', 'Guárico', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-K', 'Lara', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-M', 'Miranda', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-N', 'Monagas', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-L', 'Mérida', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-O', 'Nueva Esparta', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-P', 'Portuguesa', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-R', 'Sucre', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-T', 'Trujillo', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-S', 'Táchira', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-X', 'Vargas', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-U', 'Yaracuy', true, 35);
INSERT INTO state (code, name, enabled, country_id)  VALUES ( 'VE-V', 'Zulia', true, 35);